admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9000

static_resources:
  clusters:
  - name: cluster_nginx
    connect_timeout: 60s
    load_assignment:
      cluster_name: cluster_nginx
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 80

  - name: cluster_server
    connect_timeout: 60s
    load_assignment:
      cluster_name: cluster_server
      endpoints:
       - lb_endpoints:
           - endpoint:
               address:
                 socket_address:
                   address: 127.0.0.1
                   port_value: 3000

  - name: cluster_listener2
    connect_timeout: 60s
    load_assignment:
      cluster_name: cluster_listener2
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 2001
                    
  listeners:
    - name: listener_1
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 1001
      filter_chains:
        filters:
          - name: echo
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.echo.v3.Echo
              destination_cluster: cluster_listener2

    - name: listener_2
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 2001
      filter_chains:
        - filter_chain_match: # Receive from listener_1
            source_prefix_ranges:
              - address_prefix: 127.0.0.1 # Here we put all the listeners IP
                prefix_len: 24
            # source_ports:
              # - 999
              # - 1000
          filters:
          - name: echo
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.echo.v3.Echo # Custom Client filter
              destination_cluster: cluster_nginx

        - filters: # If no match, Receive from host (if another address than 127.0.0.1 -> e.g: 130.104.229.52) 
          - name: envoy.filters.network.tcp_proxy # Replace by custom Server filter
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: destination
              cluster: cluster_server