admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9000

static_resources:
  clusters:
  - name: cluster_nginx
    connect_timeout: 60s
    load_assignment:
      cluster_name: cluster_nginx
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 80

  - name: cluster_server
    connect_timeout: 60s
    load_assignment:
      cluster_name: cluster_server
      endpoints:
       - lb_endpoints:
           - endpoint:
               address:
                 socket_address:
                   address: 127.0.0.1
                   port_value: 3000

  - name: cluster_listener1
    connect_timeout: 60s
    load_assignment:
      cluster_name: cluster_listener1
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 1001

  - name: cluster_listener2
    connect_timeout: 60s
    load_assignment:
      cluster_name: cluster_listener2
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 2001
                    
  listeners:
    - name: listener_1
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 1001
      filter_chains:
        filters:
          - name: sender
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.sender.v3.Sender
              destination_cluster: cluster_listener2

    - name: listener_2
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 2001
      filter_chains:
        - filter_chain_match: # Receive from listener_1
            source_prefix_ranges:
              - address_prefix: 127.0.0.1 # Here we put all the listeners IP
                prefix_len: 24
            # source_ports:
              # - 999
              # - 1000
          filters:
          - name: receiver
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.receiver.v3.Receiver # Custom Client filter
              destination_cluster: cluster_nginx
          # TODO: tcp_proxy to forward to server/database
          # - name: envoy.filters.network.tcp_proxy
          #   typed_config:
          #     "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          #     stat_prefix: destination
          #     cluster: cluster_server

        - filters: # If no match, Receive from host (if another address than 127.0.0.1 -> e.g: 130.104.229.52) 
          - name: sender
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.sender.v3.Sender
              destination_cluster: cluster_listener1