admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9001

static_resources:
  clusters:
  - name: cluster_nginx
    connect_timeout: 60s
    load_assignment:
      cluster_name: cluster_nginx
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 0.0.0.0
                    port_value: 80
  - name: cluster_listener_0
    connect_timeout: 60s
    load_assignment:
      cluster_name: cluster_listener_0
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 0.0.0.0
                    port_value: 1001
  listeners:
    name: listener_1
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 2001
    filter_chains:
    - filter_chain_match: # Receive from nginx
        destination_port: 2001
        source_ports: 80
      filters:
        - name: echo
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.echo.v3.Echo
        - name: envoy.filters.network.tcp_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
            stat_prefix: destination
            cluster: cluster_listener_0
    - filter_chain_match: # Receive from listener_0
         destination_port: 2001
      filters:
        - name: echo
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.echo.v3.Echo
        - name: envoy.filters.network.tcp_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
            stat_prefix: destination
            cluster: cluster_nginx