admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 8000

static_resources:
  clusters:
  - name: cluster_node2_local
    connect_timeout: 60s
    load_assignment:
      cluster_name: cluster_node2_local
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 172.18.132.26
                    port_value: 2000

  - name: cluster_node2_memcached
    connect_timeout: 60s
    load_assignment:
      cluster_name: cluster_node2_memcached
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 172.18.132.26
                    port_value: 2001

  - name: cluster_local_service
    connect_timeout: 60s
    load_assignment:
      cluster_name: cluster_local_service
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 1000
                    
  listeners:
    - name: egress_listener_dst_node2_local # take requests from the local application related to the Envoy sidecar instance and forwards them to other services in the network
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 3000
      filter_chains:
        filters:
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: destination
              cluster: cluster_node2_local

    - name: egress_listener_dst_node2_memcached # take requests from the local application related to the Envoy sidecar instance and forwards them to other services in the network
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 3001
      filter_chains:
        filters:
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: destination
              cluster: cluster_node2_memcached
    
    - name: ingress_listener # take requests from other services in a service mesh and forward them to the local application related to the Envoy sidecar instance
      address:
        socket_address:
          address: 172.18.132.7
          port_value: 2000
      filter_chains:
        filters:
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: destination
              cluster: cluster_local_service