admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 8001

static_resources:
  clusters:
  - name: cluster_node1
    connect_timeout: 60s
    load_assignment:
      cluster_name: cluster_node1
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 172.18.132.37
                    port_value: 2000

  - name: cluster_memcached
    connect_timeout: 60s
    load_assignment:
      cluster_name: cluster_memcached
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 11211
  
  - name: cluster_nginx
    connect_timeout: 60s
    load_assignment:
      cluster_name: cluster_nginx
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 80

  - name: cluster_local_service
    connect_timeout: 60s
    load_assignment:
      cluster_name: cluster_local_service
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 1000
                    
  listeners:
    - name: egress_listener_dst_node1 # take requests from the local application related to the Envoy sidecar instance and forwards them to other services in the network
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 3000
      filter_chains:
        filters:
          - name: sender
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.sender_rdma_write_multip_write.v3.SenderRDMAWriteMultipWrite
              payload_bound: 1500
              circle_size: 200
              time_to_write: 50
              shared_buffer_size: 8388608
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: destination
              cluster: cluster_node1
    
    - name: ingress_listener_local # take requests from other services in a service mesh and forward them to the local application related to the Envoy sidecar instance
      address:
        socket_address:
          address: 172.18.132.43
          port_value: 2000
      filter_chains:
        filters:
          - name: receiver
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.receiver_rdma_write_multip_write.v3.ReceiverRDMAWriteMultipWrite
              payload_bound: 1500
              circle_size: 200
              time_to_write: 50
              shared_buffer_size: 8388608
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: destination
              cluster: cluster_local_service

    - name: ingress_listener_memcached # take requests from other services in a service mesh and forward them to the local application related to the Envoy sidecar instance
      address:
        socket_address:
          address: 172.18.132.43
          port_value: 2001
      filter_chains:
        filters:
          - name: receiver
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.receiver_rdma_write_multip_write.v3.ReceiverRDMAWriteMultipWrite
              payload_bound: 1500
              circle_size: 200
              time_to_write: 50
              shared_buffer_size: 8388608
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: destination
              cluster: cluster_memcached

    - name: ingress_listener_nginx # take requests from other services in a service mesh and forward them to the local application related to the Envoy sidecar instance
      address:
        socket_address:
          address: 172.18.132.43
          port_value: 2002
      filter_chains:
        filters:
          - name: receiver
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.receiver_rdma_write_multip_write.v3.ReceiverRDMAWriteMultipWrite
              payload_bound: 1500
              circle_size: 200
              time_to_write: 50
              shared_buffer_size: 8388608
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: destination
              cluster: cluster_nginx