admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 8000

static_resources:
  clusters:
  - name: cluster_nginx
    connect_timeout: 60s
    load_assignment:
      cluster_name: cluster_nginx
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 80

  - name: cluster_server
    connect_timeout: 60s
    load_assignment:
      cluster_name: cluster_server
      endpoints:
       - lb_endpoints:
           - endpoint:
               address:
                 socket_address:
                   address: 127.0.0.1
                   port_value: 3000

  - name: cluster_listener2
    connect_timeout: 60s
    load_assignment:
      cluster_name: cluster_listener2
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 2001
                    
  listeners:
    - name: listener_2
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 2001
      filter_chains:
        filters:
          - name: receiver
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.receiver.v3.Receiver
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: destination
              cluster: cluster_server # Can be changed by cluster_nginx