admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9000
      
static_resources:
  clusters:
  - name: cluster_listener2
    connect_timeout: 60s
    load_assignment:
      cluster_name: cluster_listener2
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 2001

  - name: cluster_server
    connect_timeout: 60s
    load_assignment:
      cluster_name: cluster_server
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 3000
                    
  listeners:
    - name: listener_1
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 1001
      filter_chains:
        filters:
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: destination
              cluster: cluster_listener2